os: linux
dist: bionic
language: c

addons:
  apt:
    packages: &default_deps
      - help2man

# env:
#   global:
#     - VERBOSE=1

matrix:
  include:
    - os: linux
    - os: osx
    - compiler: gcc
      addons:
        apt:
          packages:
            - *default_deps
    - env:
        - ASAN=yes
        - LSAN_OPTIONS="verbosity=1:log_threads=1"

script:
  - ./bootstrap
  - if [[ "$ASAN" == "yes" ]]; then ./configure --enable-silent-rules CFLAGS="-g3 -fsanitize=address -fsanitize=undefined" LDFLAGS="-fsanitize=address -fsanitize=undefined" LOG_ENV="LD_PRELOAD=/usr/lib/gcc/x86_64-linux-gnu/7/libasan.so"; else ./configure --enable-silent-rules; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install help2man; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make check; else make distcheck; fi
