#[allow(unused)]
#[derive(Debug, Copy, Clone, Hash, Eq, PartialEq)]
#[repr(u8)]
pub enum Insn1 {
    CallI    = 0x0,
    PushI    = 0x1,
    PushrelI = 0x2,
    JumpI    = 0x3,
    JumpzI   = 0x4,
    Trap     = 0x5,
}

#[allow(non_camel_case_types)]
#[allow(unused)]
pub enum Insn2 {
    Nop            = 0x00,
    Not            = 0x01,
    And            = 0x02,
    Or             = 0x03,
    Xor            = 0x04,
    LShift         = 0x05,
    RShift         = 0x06,
    ARShift        = 0x07,
    Pop            = 0x08,
    Dup            = 0x09,
    Set            = 0x0a,
    Swap           = 0x0b,
    Jump           = 0x0c,
    JumpZ          = 0x0d,
    Call           = 0x0e,
    Ret            = 0x0f,
    Load           = 0x10,
    Store          = 0x11,
    Load1          = 0x12,
    Store1         = 0x13,
    Load2          = 0x14,
    Store2         = 0x15,
    Load4          = 0x16,
    Store4         = 0x17,
    Neg            = 0x20,
    Add            = 0x21,
    Mul            = 0x22,
    DivMod         = 0x23,
    UDivMod        = 0x24,
    Eq             = 0x25,
    Lt             = 0x26,
    ULt            = 0x27,
    PushS          = 0x28,
    PopS           = 0x29,
    DupS           = 0x2a,
    Catch          = 0x2b,
    Throw          = 0x2c,
    Break          = 0x2d,
    Word_Bytes     = 0x2e,
    Get_SSize      = 0x31,
    Get_SP         = 0x32,
    Set_SP         = 0x33,
    Get_DSize      = 0x34,
    Get_DP         = 0x35,
    Set_DP         = 0x36,
    Get_Handler_SP = 0x37,
}