.TH BEEI "1" "July 2018" "Bee" "User Commands"
.SH NAME
beei \- Bee Forth virtual machine interactive wrapper
.SH SYNOPSIS
.B beei
[\fI\,OPTION\/\fR...] [\fI\,OBJECT\-FILE ARGUMENT\/\fR...]
.SH DESCRIPTION
Run Bee wrapped with \fBrlwrap\fR to provide command-line editing and history.
.SH FILES
.TP
\fI~/.bee_history\fR
File in which the command-line history is saved.
.SH "SEE ALSO"
.BR bee (1),
.BR bee-dump (1),
.BR rlwrap (1)
.SH "REPORTING BUGS"
Report bugs to rrt@sc3d.org.
.PP
\(co Reuben Thomas 1995\-2018
.br
Bee comes with ABSOLUTELY NO WARRANTY.
.br
You may redistribute copies of Bee
under the terms of the GNU General Public License.
.br
For more information about these matters, see the file named COPYING.
