#define ALIGN bee_ALIGN
#define ARSHIFT bee_ARSHIFT
#define DEFAULT_STACK_SIZE bee_DEFAULT_STACK_SIZE
#define DOUBLE_WORD bee_DOUBLE_WORD
#define DUWORD bee_DUWORD
#define ERROR_BREAK bee_ERROR_BREAK
#define ERROR_INVALID_FUNCTION bee_ERROR_INVALID_FUNCTION
#define ERROR_INVALID_LIBRARY bee_ERROR_INVALID_LIBRARY
#define ERROR_INVALID_LOAD bee_ERROR_INVALID_LOAD
#define ERROR_INVALID_OPCODE bee_ERROR_INVALID_OPCODE
#define ERROR_INVALID_STORE bee_ERROR_INVALID_STORE
#define ERROR_OK bee_ERROR_OK
#define ERROR_STACK_OVERFLOW bee_ERROR_STACK_OVERFLOW
#define ERROR_STACK_UNDERFLOW bee_ERROR_STACK_UNDERFLOW
#define ERROR_UNALIGNED_ADDRESS bee_ERROR_UNALIGNED_ADDRESS
#define HANDLER_SP bee_HANDLER_SP
#define init bee_init
#define init_defaults bee_init_defaults
#define IS_ALIGNED bee_IS_ALIGNED
#define IR bee_IR
#define load_byte bee_load_byte
#define load_object bee_load_object
#define load_word bee_load_word
#define LSHIFT bee_LSHIFT
#define M0 bee_M0
#define MSIZE bee_MSIZE
#define PC bee_PC
#define POP bee_POP
#define POP_RETURN bee_POP_RETURN
#define pop_stack bee_pop_stack
#define PUSH bee_PUSH
#define PUSH_DOUBLE bee_PUSH_DOUBLE
#define PUSH_RETURN bee_PUSH_RETURN
#define push_stack bee_push_stack
#define S0 bee_S0
#define register_args bee_register_args
#define SP bee_SP
#define SSIZE bee_SSIZE
#define run bee_run
#define D0 bee_D0
#define DP bee_DP
#define DSIZE bee_DSIZE
#define stack_position bee_stack_position
#define store_byte bee_store_byte
#define store_word bee_store_word
#define UWORD bee_UWORD
#define WORD bee_WORD
#define WORD_BIT bee_WORD_BIT
#define WORD_BYTES bee_WORD_BYTES
#define WORD_MAX bee_WORD_MAX
#define WORD_MIN bee_WORD_MIN
