#define ALIGN bee_ALIGN
#define ARSHIFT bee_ARSHIFT
#define ass bee_ass
#define ass_byte bee_ass_byte
#define ass_goto bee_ass_goto
#define BAD bee_BAD
#define byte_size bee_byte_size
#define call bee_call
#define CHAR_MASK bee_CHAR_MASK
#define DEFAULT_STACK_SIZE bee_DEFAULT_STACK_SIZE
#define disass bee_disass
#define DOUBLE_WORD bee_DOUBLE_WORD
#define DUWORD bee_DUWORD
#define ERROR_BREAK bee_ERROR_BREAK
#define ERROR_INVALID_LOAD bee_ERROR_INVALID_LOAD
#define ERROR_INVALID_OPCODE bee_ERROR_INVALID_OPCODE
#define ERROR_INVALID_STORE bee_ERROR_INVALID_STORE
#define ERROR_OK bee_ERROR_OK
#define ERROR_STACK_OVERFLOW bee_ERROR_STACK_OVERFLOW
#define ERROR_STACK_UNDERFLOW bee_ERROR_STACK_UNDERFLOW
#define error_to_msg bee_error_to_msg
#define ERROR_UNALIGNED_ADDRESS bee_ERROR_UNALIGNED_ADDRESS
#define HANDLER_RP bee_HANDLER_RP
#define HASHR bee_HASHR
#define HASHS bee_HASHS
#define I bee_I
#define init bee_init
#define init_defaults bee_init_defaults
#define IS_ALIGNED bee_IS_ALIGNED
#define label bee_label
#define load_byte bee_load_byte
#define load_object bee_load_object
#define load_word bee_load_word
#define M0 bee_M0
#define memory bee_memory
#define MEMORY bee_MEMORY
#define mem_realloc bee_mem_realloc
#define PC bee_PC
#define plit bee_plit
#define POINTER_W bee_POINTER_W
#define POP bee_POP
#define POP_RETURN bee_POP_RETURN
#define pop_stack bee_pop_stack
#define push bee_push
#define PUSH bee_PUSH
#define PUSH_DOUBLE bee_PUSH_DOUBLE
#define pushrel bee_pushrel
#define PUSH_RETURN bee_PUSH_RETURN
#define push_stack bee_push_stack
#define R0 bee_R0
#define register_args bee_register_args
#define RP bee_RP
#define RSIZE bee_RSIZE
#define run bee_run
#define S0 bee_S0
#define show_data_stack bee_show_data_stack
#define show_return_stack bee_show_return_stack
#define single_step bee_single_step
#define SP bee_SP
#define SSIZE bee_SSIZE
#define STACK_DIRECTION bee_STACK_DIRECTION
#define stack_position bee_stack_position
#define STACK_UNDERFLOW bee_STACK_UNDERFLOW
#define store_byte bee_store_byte
#define store_word bee_store_word
#define toass bee_toass
#define UWORD bee_UWORD
#define val_data_stack bee_val_data_stack
#define word bee_word
#define WORD bee_WORD
#define WORD_BIT bee_WORD_BIT
#define WORD_BYTES bee_WORD_BYTES
#define WORD_MAX bee_WORD_MAX
#define WORD_MIN bee_WORD_MIN
#define WORD_pointer bee_WORD_pointer
